AWSTemplateFormatVersion: '2010-09-09'
Description: 'Monitoring resources for Currency Exchange platform'

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project

  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)

  EC2AutoScalingGroupName:
    Type: String
    Description: Name of the EC2 Auto Scaling Group

  AuroraClusterIdentifier:
    Type: String
    Description: Aurora cluster identifier (not ARN, just the name)

  ALBFullName:
    Type: String
    Description: Full name of the Application Load Balancer

  NotificationEmail:
    Type: String
    Description: Email address for alarm notifications

  LogRetentionDays:
    Type: Number
    Description: CloudWatch log retention in days
    Default: 30
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365]

Resources:
  # ==========================================
  # SNS TOPIC FOR ALERTS
  # ==========================================

  AlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${ProjectName}-${Environment}-alerts-topic"
      DisplayName: !Sub "${ProjectName} ${Environment} Alerts"
      Subscription:
        - Protocol: email
          Endpoint: !Ref NotificationEmail
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-alerts-topic"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # ==========================================
  # CLOUDWATCH LOG GROUP
  # ==========================================

  AppLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/ec2/${ProjectName}-${Environment}-app"
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-log-group"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # ==========================================
  # EC2 MONITORING
  # ==========================================

  EC2HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-ec2-high-cpu"
      AlarmDescription: "EC2 CPU utilization is high"
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref EC2AutoScalingGroupName
      AlarmActions:
        - !Ref AlertsTopic
      OKActions:
        - !Ref AlertsTopic
      TreatMissingData: notBreaching
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-ec2-cpu-alarm"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # ==========================================
  # DATABASE MONITORING
  # ==========================================

  AuroraHighConnections:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-aurora-high-connections"
      AlarmDescription: "Aurora database connections are high"
      MetricName: DatabaseConnections
      Namespace: AWS/RDS
      Statistic: Average
      Period: 60
      EvaluationPeriods: 2
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBClusterIdentifier
          Value: !Ref AuroraClusterIdentifier
      AlarmActions:
        - !Ref AlertsTopic
      OKActions:
        - !Ref AlertsTopic
      TreatMissingData: notBreaching
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-aurora-connections-alarm"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  AuroraCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-aurora-high-cpu"
      AlarmDescription: "Aurora CPU utilization is high"
      MetricName: CPUUtilization
      Namespace: AWS/RDS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DBClusterIdentifier
          Value: !Ref AuroraClusterIdentifier
      AlarmActions:
        - !Ref AlertsTopic
      OKActions:
        - !Ref AlertsTopic
      TreatMissingData: notBreaching
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-aurora-cpu-alarm"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # ==========================================
  # ALB MONITORING
  # ==========================================

  ALBHighErrorRate:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-alb-high-error-rate"
      AlarmDescription: "ALB 5XX error rate is high"
      MetricName: HTTPCode_Target_5XX_Count
      Namespace: AWS/ApplicationELB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref ALBFullName
      AlarmActions:
        - !Ref AlertsTopic
      OKActions:
        - !Ref AlertsTopic
      TreatMissingData: notBreaching
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-alb-error-alarm"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  ALBHighResponseTime:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${ProjectName}-${Environment}-alb-high-response-time"
      AlarmDescription: "ALB response time is high"
      MetricName: TargetResponseTime
      Namespace: AWS/ApplicationELB
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 2.0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref ALBFullName
      AlarmActions:
        - !Ref AlertsTopic
      OKActions:
        - !Ref AlertsTopic
      TreatMissingData: notBreaching
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-alb-response-time-alarm"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

  # ==========================================
  # CLOUDWATCH DASHBOARD
  # ==========================================

  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "${ProjectName}-${Environment}-dashboard"
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/ApplicationELB", "RequestCount", "LoadBalancer", "${ALBFullName}"],
                  ["AWS/ApplicationELB", "TargetResponseTime", "LoadBalancer", "${ALBFullName}"],
                  ["AWS/ApplicationELB", "HTTPCode_Target_5XX_Count", "LoadBalancer", "${ALBFullName}"]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "ALB Performance Metrics",
                "yAxis": {
                  "left": {
                    "min": 0
                  }
                }
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  ["AWS/EC2", "CPUUtilization", "AutoScalingGroupName", "${EC2AutoScalingGroupName}"],
                  ["AWS/RDS", "CPUUtilization", "DBClusterIdentifier", "${AuroraClusterIdentifier}"],
                  ["AWS/RDS", "DatabaseConnections", "DBClusterIdentifier", "${AuroraClusterIdentifier}"]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "Infrastructure Metrics"
              }
            }
          ]
        }

Outputs:
  # ==========================================
  # MONITORING OUTPUTS
  # ==========================================

  AlertsTopicArn:
    Description: "SNS topic ARN for alert notifications"
    Value: !Ref AlertsTopic
    Export:
      Name: !Sub "${AWS::StackName}-alerts-topic-arn"

  AppLogGroupName:
    Description: "CloudWatch Log Group for the EC2 application"
    Value: !Ref AppLogGroup
    Export:
      Name: !Sub "${AWS::StackName}-log-group-name"

  DashboardURL:
    Description: "CloudWatch Dashboard URL"
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${ProjectName}-${Environment}-dashboard"

  MonitoringSetup:
    Description: "Monitoring configuration summary"
    Value: !Sub |
      Alarms: EC2 CPU, Aurora CPU/Connections, ALB Errors/Response Time
      Notifications: ${NotificationEmail}
      Dashboard: ${ProjectName}-${Environment}-dashboard
      Log Retention: ${LogRetentionDays} days
