---
AWSTemplateFormatVersion: "2010-09-09"
Description: "VPC for Currency Exchange Platform - Multi-AZ"

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
  VpcCidr:
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-vpc"

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-igw"

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # =====================================
  # PUBLIC SUBNETS
  # =====================================
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-public-1"

  # =====================================
  # PRIVATE SUBNETS (Multi-AZ for Redis)
  # =====================================
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.11.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-private-1"

  # ✅ NEW: Second private subnet for Redis Multi-AZ
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.12.0/24
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-private-2"
        - Key: Purpose
          Value: "Required for Redis Multi-AZ deployment"

  # =====================================
  # DATABASE SUBNETS (MUST BE MULTI-AZ)
  # =====================================
  DatabaseSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.21.0/24
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-database-1"

  # CRITICAL: Aurora requires minimum 2 AZs
  DatabaseSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.22.0/24
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-database-2"
        - Key: Purpose
          Value: "Required for Aurora Multi-AZ deployment"

  # =====================================
  # ROUTE TABLES
  # =====================================
  RouteTablePublic:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-public-rt"

  RoutePublic:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTablePublic
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # =====================================
  # ROUTE TABLE ASSOCIATIONS
  # =====================================
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref RouteTablePublic

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub "${ProjectName}-${Environment}-vpc-id"

  VpcCidr:
    Description: VPC CIDR block
    Value: !Ref VpcCidr
    Export:
      Name: !Sub "${ProjectName}-${Environment}-vpc-cidr"

  PublicSubnetIds:
    Description: Public subnet IDs
    Value: !Ref PublicSubnet1
    Export:
      Name: !Sub "${ProjectName}-${Environment}-public-subnets"

  PrivateSubnetIds:
    Description: Private subnet IDs (Multi-AZ for Redis)
    Value: !Join [",", [!Ref PrivateSubnet1, !Ref PrivateSubnet2]]
    Export:
      Name: !Sub "${ProjectName}-${Environment}-private-subnets"

  DatabaseSubnetIds:
    Description: Database subnet IDs (Multi-AZ for Aurora)
    Value: !Join [",", [!Ref DatabaseSubnet1, !Ref DatabaseSubnet2]]
    Export:
      Name: !Sub "${ProjectName}-${Environment}-database-subnets"

  DeploymentNote:
    Description: Important deployment information
    Value: "Private and Database subnets span 2 AZs for Redis and Aurora Multi-AZ requirements"
