version: '3.8'

services:
  currency-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
